time="2021-09-08T12:01:17Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:01:17Z" level=error msg="Error while starting server: accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:01:17Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:01:17Z" level=error msg="Error while starting server: accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:01:17Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:01:17Z" level=error msg="Error while starting server: accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:01:17Z" level=error msg="Error while starting server: http: Server closed" entryPointName=websecure
time="2021-09-08T12:01:17Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2021-09-08T12:01:17Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-09-08T12:03:39Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:03:39Z" level=error msg="Error while starting server: accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:03:39Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-09-08T12:03:39Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:03:39Z" level=error msg="Error while starting server: http: Server closed" entryPointName=websecure
time="2021-09-08T12:03:39Z" level=error msg="Error while starting server: http: Server closed" entryPointName=websecure
time="2021-09-08T12:03:39Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:03:39Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2021-09-08T12:03:39Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2021-09-08T12:03:39Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:03:39Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:11:20Z" level=error msg="Unable to obtain ACME certificate for domains \"datalab.humlab.umu.se,gitlab.datalab.humlab.umu.se,idp.datalab.humlab.umu.se,app.datalab.humlab.umu.se,labjs.datalab.humlab.umu.se\": unable to generate a certificate for the domains [datalab.humlab.umu.se gitlab.datalab.humlab.umu.se idp.datalab.humlab.umu.se app.datalab.humlab.umu.se labjs.datalab.humlab.umu.se]: error: one or more domains had a problem:\n[app.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://app.datalab.humlab.umu.se/.well-known/acme-challenge/5C-hVb15YioeOeN438kMieutDKEVKnOV6lxZ-3WjHnc [130.239.1.154]: 404\n[datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://datalab.humlab.umu.se/.well-known/acme-challenge/mWPZ7zj9wk7WVeh-eBpOG6gR8sjrqk3SMbcZ9kJtzJk [130.239.1.154]: 404\n[gitlab.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://gitlab.datalab.humlab.umu.se/.well-known/acme-challenge/NU6XtAhc91p7KisYz1ujHlzvZkwQak-YrWuQW9C90oU [130.239.1.154]: 404\n[idp.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://idp.datalab.humlab.umu.se/.well-known/acme-challenge/7PhQN-9plGrD7NFJ56iTQy2Pf-LcKGELJ8RLwdGmbqM [130.239.1.154]: 404\n[labjs.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://labjs.datalab.humlab.umu.se/.well-known/acme-challenge/CSWuGbbhk4ZF7jPHIyKDzXp66-QSUtdkM75K8WAJQ68 [130.239.1.154]: 404\n" routerName=datalabRouterHttps@file rule="Host(`datalab.humlab.umu.se`) || Host(`gitlab.datalab.humlab.umu.se`) || Host(`idp.datalab.humlab.umu.se`) || Host(`app.datalab.humlab.umu.se`) || Host(`labjs.datalab.humlab.umu.se`)" providerName=cr1.acme
time="2021-09-08T12:12:16Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:12:16Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:12:16Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-09-08T12:12:16Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:12:16Z" level=error msg="Error while starting server: http: Server closed" entryPointName=web
time="2021-09-08T12:12:16Z" level=error msg="Error while starting server: http: Server closed" entryPointName=websecure
time="2021-09-08T12:12:16Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2021-09-08T12:12:16Z" level=error msg="Error while starting server: http: Server closed" entryPointName=traefik
time="2021-09-08T12:12:16Z" level=error msg="Error while starting server: http: Server closed" entryPointName=websecure
time="2021-09-08T12:12:16Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:12:16Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:12:16Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:13:33Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:13:33Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:13:33Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:13:33Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:13:33Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:13:33Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:16:58Z" level=error msg="Unable to obtain ACME certificate for domains \"localtest.me,gitlab.localtest.me,idp.localtest.me,app.localtest.me,labjs.localtest.me\": unable to generate a certificate for the domains [localtest.me gitlab.localtest.me idp.localtest.me app.localtest.me labjs.localtest.me]: error: one or more domains had a problem:\n[app.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for app.localtest.me\n[gitlab.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for gitlab.localtest.me\n[idp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for idp.localtest.me\n[labjs.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for labjs.localtest.me\n[localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for localtest.me\n" providerName=cr1.acme routerName=hirdRouterHttps@file rule="Host(`localtest.me`) || Host(`gitlab.localtest.me`) || Host(`idp.localtest.me`) || Host(`app.localtest.me`) || Host(`labjs.localtest.me`)"
time="2021-09-08T12:17:58Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:17:58Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:17:58Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T12:17:58Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T12:17:58Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T12:17:58Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T13:23:33Z" level=error msg="Unable to obtain ACME certificate for domains \"localtest.me,gitlab.localtest.me,idp.localtest.me,app.localtest.me,labjs.localtest.me\": unable to generate a certificate for the domains [localtest.me gitlab.localtest.me idp.localtest.me app.localtest.me labjs.localtest.me]: error: one or more domains had a problem:\n[app.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for app.localtest.me\n[gitlab.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for gitlab.localtest.me\n[idp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for idp.localtest.me\n[labjs.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for labjs.localtest.me\n[localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for localtest.me\n" providerName=cr1.acme routerName=hirdRouterHttps@file rule="Host(`localtest.me`) || Host(`gitlab.localtest.me`) || Host(`idp.localtest.me`) || Host(`app.localtest.me`) || Host(`labjs.localtest.me`)"
time="2021-09-08T13:29:30Z" level=error msg="Unable to obtain ACME certificate for domains \"datalab.humlab.umu.se,gitlab.datalab.humlab.umu.se,idp.datalab.humlab.umu.se,app.datalab.humlab.umu.se,labjs.datalab.humlab.umu.se\": unable to generate a certificate for the domains [datalab.humlab.umu.se gitlab.datalab.humlab.umu.se idp.datalab.humlab.umu.se app.datalab.humlab.umu.se labjs.datalab.humlab.umu.se]: error: one or more domains had a problem:\n[app.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://app.datalab.humlab.umu.se/.well-known/acme-challenge/BgSzZt01XEjxiFLJXfxeuzA_ubtwY7VuVwYdSOQ5VTk [130.239.1.154]: 404\n[datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://datalab.humlab.umu.se/.well-known/acme-challenge/DG_J4j2brocOUsjlQgoCgZaz4EAAAGGhKlrqy9947sE [130.239.1.154]: 404\n[gitlab.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://gitlab.datalab.humlab.umu.se/.well-known/acme-challenge/HXCysyc8iz3s_3893wzLNB9GdMcEKZAhksS3CLb-l6s [130.239.1.154]: 404\n[idp.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://idp.datalab.humlab.umu.se/.well-known/acme-challenge/8dXuQmwHsiu48D9qTDg9rAGb-lEutJorfy40o4_CHGA [130.239.1.154]: 404\n[labjs.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://labjs.datalab.humlab.umu.se/.well-known/acme-challenge/OmLGMpRLIK5C3SvvsvkK-W4GiWL6q5XBSPOOEXc1040 [130.239.1.154]: 404\n" providerName=cr1.acme routerName=datalabRouterHttps@file rule="Host(`datalab.humlab.umu.se`) || Host(`gitlab.datalab.humlab.umu.se`) || Host(`idp.datalab.humlab.umu.se`) || Host(`app.datalab.humlab.umu.se`) || Host(`labjs.datalab.humlab.umu.se`)"
time="2021-09-08T13:51:25Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T13:51:25Z" level=error msg="Error while starting server: accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T13:51:25Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T13:51:25Z" level=error msg="Error while starting server: accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T13:51:25Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T13:51:25Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T13:52:00Z" level=error msg="Unable to obtain ACME certificate for domains \"localtest.me,gitlab.localtest.me,idp.localtest.me,app.localtest.me,labjs.localtest.me\": unable to generate a certificate for the domains [localtest.me gitlab.localtest.me idp.localtest.me app.localtest.me labjs.localtest.me]: error: one or more domains had a problem:\n[app.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for app.localtest.me\n[gitlab.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for gitlab.localtest.me\n[idp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for idp.localtest.me\n[labjs.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for labjs.localtest.me\n[localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for localtest.me\n" providerName=cr1.acme routerName=hirdRouterHttps@file rule="Host(`localtest.me`) || Host(`gitlab.localtest.me`) || Host(`idp.localtest.me`) || Host(`app.localtest.me`) || Host(`labjs.localtest.me`)"
time="2021-09-08T13:58:27Z" level=error msg="Unable to obtain ACME certificate for domains \"datalab.humlab.umu.se,gitlab.datalab.humlab.umu.se,idp.datalab.humlab.umu.se,app.datalab.humlab.umu.se,labjs.datalab.humlab.umu.se\": unable to generate a certificate for the domains [datalab.humlab.umu.se gitlab.datalab.humlab.umu.se idp.datalab.humlab.umu.se app.datalab.humlab.umu.se labjs.datalab.humlab.umu.se]: error: one or more domains had a problem:\n[app.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://app.datalab.humlab.umu.se/.well-known/acme-challenge/wiSy6BFzUlFwN4jr8stGehRQNKkfGgnBFhvOl9VOVbo [130.239.1.154]: 404\n[datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://datalab.humlab.umu.se/.well-known/acme-challenge/lnOUDKBg5mswzRmnTdYN7JaRg6yPvKmcaThElmq46mA [130.239.1.154]: 404\n[gitlab.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://gitlab.datalab.humlab.umu.se/.well-known/acme-challenge/qdGEdv9rIduLezVoq5VpJxJiE70iQTuMa9FJKWqcLHw [130.239.1.154]: 404\n[idp.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://idp.datalab.humlab.umu.se/.well-known/acme-challenge/XL9fhliBKb5iihMPO7foVOfFCZonFnN5afFqYdwMoBg [130.239.1.154]: 404\n[labjs.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://labjs.datalab.humlab.umu.se/.well-known/acme-challenge/HQ7LkTSc1XigVt23Yg7CfpDJPhGcvox40ITSHqD_QlQ [130.239.1.154]: 404\n" providerName=cr1.acme routerName=datalabRouterHttps@file rule="Host(`datalab.humlab.umu.se`) || Host(`gitlab.datalab.humlab.umu.se`) || Host(`idp.datalab.humlab.umu.se`) || Host(`app.datalab.humlab.umu.se`) || Host(`labjs.datalab.humlab.umu.se`)"
time="2021-09-08T13:59:09Z" level=error msg="Unable to obtain ACME certificate for domains \"localtest.me,gitlab.localtest.me,idp.localtest.me,app.localtest.me,labjs.localtest.me\": unable to generate a certificate for the domains [localtest.me gitlab.localtest.me idp.localtest.me app.localtest.me labjs.localtest.me]: error: one or more domains had a problem:\n[app.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for app.localtest.me\n[gitlab.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for gitlab.localtest.me\n[idp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for idp.localtest.me\n[labjs.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for labjs.localtest.me\n[localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for localtest.me\n" providerName=cr1.acme routerName=hirdRouterHttps@file rule="Host(`localtest.me`) || Host(`gitlab.localtest.me`) || Host(`idp.localtest.me`) || Host(`app.localtest.me`) || Host(`labjs.localtest.me`)"
time="2021-09-08T13:59:20Z" level=error msg="Unable to obtain ACME certificate for domains \"localtest.me,gitlab.localtest.me,idp.localtest.me,app.localtest.me,labjs.localtest.me,octra.localtest.me,emu-webapp.localtest.me\": unable to generate a certificate for the domains [octra.localtest.me emu-webapp.localtest.me]: error: one or more domains had a problem:\n[app.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for app.localtest.me\n[emu-webapp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for emu-webapp.localtest.me\n[gitlab.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for gitlab.localtest.me\n[idp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for idp.localtest.me\n[labjs.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for labjs.localtest.me\n[localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for localtest.me\n[octra.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for octra.localtest.me\n" providerName=cr1.acme routerName=hirdRouterHttps@file rule="Host(`localtest.me`) || Host(`gitlab.localtest.me`) || Host(`idp.localtest.me`) || Host(`app.localtest.me`) || Host(`labjs.localtest.me`) || Host(`octra.localtest.me`) || Host(`emu-webapp.localtest.me`)"
time="2021-09-08T13:59:21Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T13:59:21Z" level=error msg="Error while starting server: accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T13:59:21Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T13:59:21Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T13:59:21Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T13:59:21Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T13:59:37Z" level=error msg="Unable to obtain ACME certificate for domains \"localtest.me,gitlab.localtest.me,idp.localtest.me,app.localtest.me,labjs.localtest.me,octra.localtest.me,emu-webapp.localtest.me\": unable to generate a certificate for the domains [localtest.me gitlab.localtest.me idp.localtest.me app.localtest.me labjs.localtest.me octra.localtest.me emu-webapp.localtest.me]: error: one or more domains had a problem:\n[app.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for app.localtest.me\n[emu-webapp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for emu-webapp.localtest.me\n[gitlab.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for gitlab.localtest.me\n[idp.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for idp.localtest.me\n[labjs.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for labjs.localtest.me\n[localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for localtest.me\n[octra.localtest.me] acme: error: 400 :: urn:ietf:params:acme:error:dns :: No valid IP addresses found for octra.localtest.me\n" providerName=cr1.acme routerName=hirdRouterHttps@file rule="Host(`localtest.me`) || Host(`gitlab.localtest.me`) || Host(`idp.localtest.me`) || Host(`app.localtest.me`) || Host(`labjs.localtest.me`) || Host(`octra.localtest.me`) || Host(`emu-webapp.localtest.me`)"
time="2021-09-08T14:04:59Z" level=error msg="Unable to obtain ACME certificate for domains \"datalab.humlab.umu.se,gitlab.datalab.humlab.umu.se,idp.datalab.humlab.umu.se,app.datalab.humlab.umu.se,labjs.datalab.humlab.umu.se\": unable to generate a certificate for the domains [datalab.humlab.umu.se gitlab.datalab.humlab.umu.se idp.datalab.humlab.umu.se app.datalab.humlab.umu.se labjs.datalab.humlab.umu.se]: error: one or more domains had a problem:\n[app.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://app.datalab.humlab.umu.se/.well-known/acme-challenge/Zt3DWnTx_JFLYassvPvqTVZj_cc5-Y6Z-wACFN2ETP4 [130.239.1.154]: 404\n[datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://datalab.humlab.umu.se/.well-known/acme-challenge/u-Z2a2fNhe6fSo29LlPvgtatRm2T9nXgJdBWIcK4jy0 [130.239.1.154]: 404\n[gitlab.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://gitlab.datalab.humlab.umu.se/.well-known/acme-challenge/WkvXq1iJ34O3Rrplbf0qLihvIel2RAEZOWJY_0Hr5Cs [130.239.1.154]: 404\n[idp.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://idp.datalab.humlab.umu.se/.well-known/acme-challenge/WwG06C7j-62Nc6stgiMgzzmtHeF_SWyVy6wJxE3cx2o [130.239.1.154]: 404\n[labjs.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://labjs.datalab.humlab.umu.se/.well-known/acme-challenge/0lh4ea8ko_RtkGCMYwk7RoNhZoJUgMLXBUwlKKSX35s [130.239.1.154]: 404\n" routerName=datalabRouterHttps@file rule="Host(`datalab.humlab.umu.se`) || Host(`gitlab.datalab.humlab.umu.se`) || Host(`idp.datalab.humlab.umu.se`) || Host(`app.datalab.humlab.umu.se`) || Host(`labjs.datalab.humlab.umu.se`)" providerName=cr1.acme
time="2021-09-08T14:19:50Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T14:19:50Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T14:19:50Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T14:19:50Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T14:19:50Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T14:19:50Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T14:20:48Z" level=error msg="Unable to obtain ACME certificate for domains \"localtest.me,gitlab.localtest.me,idp.localtest.me,app.localtest.me,labjs.localtest.me,octra.localtest.me,emu-webapp.localtest.me\": unable to generate a certificate for the domains [localtest.me gitlab.localtest.me idp.localtest.me app.localtest.me labjs.localtest.me octra.localtest.me emu-webapp.localtest.me]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/" rule="Host(`localtest.me`) || Host(`gitlab.localtest.me`) || Host(`idp.localtest.me`) || Host(`app.localtest.me`) || Host(`labjs.localtest.me`) || Host(`octra.localtest.me`) || Host(`emu-webapp.localtest.me`)" providerName=cr1.acme routerName=hirdRouterHttps@file
time="2021-09-08T14:26:22Z" level=error msg="Unable to obtain ACME certificate for domains \"datalab.humlab.umu.se,gitlab.datalab.humlab.umu.se,idp.datalab.humlab.umu.se,app.datalab.humlab.umu.se,labjs.datalab.humlab.umu.se\": unable to generate a certificate for the domains [datalab.humlab.umu.se gitlab.datalab.humlab.umu.se idp.datalab.humlab.umu.se app.datalab.humlab.umu.se labjs.datalab.humlab.umu.se]: error: one or more domains had a problem:\n[app.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://app.datalab.humlab.umu.se/.well-known/acme-challenge/4e2W8Btp4waMqfRgVXAoop0CEZk8Q2tXa-aDC6PpZd4 [130.239.1.154]: 404\n[datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://datalab.humlab.umu.se/.well-known/acme-challenge/EmdVvX5z1k-e81ojMKFozTx64-XD9T9izhmgW_o5nnc [130.239.1.154]: 404\n[gitlab.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://gitlab.datalab.humlab.umu.se/.well-known/acme-challenge/AnfExObpC8GUhrHYrWr2ct5cjJ3_Ab6wZS8CFBtTrjo [130.239.1.154]: 404\n[idp.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://idp.datalab.humlab.umu.se/.well-known/acme-challenge/bpGy1Ivsbuj-Akv24VnwC97JbjZnjP9-_82eBExvl3A [130.239.1.154]: 404\n[labjs.datalab.humlab.umu.se] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://labjs.datalab.humlab.umu.se/.well-known/acme-challenge/7Jm6IZGQ2blJX-0Z7kYEnIgEsZmMQh9lmMiKOj4Q2Kw [130.239.1.154]: 404\n" providerName=cr1.acme routerName=datalabRouterHttps@file rule="Host(`datalab.humlab.umu.se`) || Host(`gitlab.datalab.humlab.umu.se`) || Host(`idp.datalab.humlab.umu.se`) || Host(`app.datalab.humlab.umu.se`) || Host(`labjs.datalab.humlab.umu.se`)"
time="2021-09-08T14:45:56Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T14:45:56Z" level=error msg="Error while starting server: accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2021-09-08T14:45:56Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T14:45:56Z" level=error msg="Error while starting server: accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2021-09-08T14:45:56Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2021-09-08T14:45:56Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
